In [1]:
# 201701670 송수빈
# 1번 Forwardpropagation
import numpy as np
import scipy.special

#actication_function=lambda x: scipy.special.expit(x)
actication_function=lambda x: 1/(1+np.exp(-x))

Input=np.array([0.9,0.1,0.8], ndmin=2).T
#Input=numpy.matrix([[0.9],[0.1],[0.8]])
print("input.T\n", input)

Winput_hidden=np.matrix([[0.9,0.3,0.4],[0.2,0.8,0.2],[0.1,0.5,0.6]])
print("Winput_hidden\n", Winput_hidden)

Whidden_output=np.matrix([[0.3,0.7,0.5],[0.6,0.5,0.2],[0.8,0.1,0.9]])
print("Whidden_output\n", Whidden_output)

Xhidden=np.dot(Winput_hidden,Input)
print("Xhidden\n", Xhidden)

Ohidden=actication_function(Xhidden)
print("Ohidden\n", Ohidden)

Xoutput=np.dot(Whidden_output,Ohidden)
print("Xoutput\n", Xoutput)

output=actication_function(Xoutput)
print("output\n", output)

input.T
 <bound method Kernel.raw_input of <ipykernel.ipkernel.IPythonKernel object at 0x000001E00C10CEC8>>
Winput_hidden
 [[0.9 0.3 0.4]
 [0.2 0.8 0.2]
 [0.1 0.5 0.6]]
Whidden_output
 [[0.3 0.7 0.5]
 [0.6 0.5 0.2]
 [0.8 0.1 0.9]]
Xhidden
 [[1.16]
 [0.42]
 [0.62]]
Ohidden
 [[0.76133271]
 [0.60348325]
 [0.65021855]]
Xoutput
 [[0.97594736]
 [0.88858496]
 [1.25461119]]
output
 [[0.72630335]
 [0.70859807]
 [0.77809706]]


In [2]:
# 2번 Backwardpropagation
import numpy as np
import scipy.special

Winput_hidden=np.array([[3.0,2.0],[1.0,7.0]])
#Winput_hidden=np.matrix([[3.0,2.0],[1.0,7.0]])
print("Winput_hidden\n", Winput_hidden)

Whidden_output=np.array([[2.0,3.0],[1.0,4.0]])
#Whidden_output=np.matrix([[2.0,3.0],[1.0,4.0]])
print("Whidden_output\n", Whidden_output)

Eoutput=np.array([0.8,0.5], ndmin=2).T
print("Eoutput\n", Eoutput)
print("Eoutput_sum\n", Eoutput.sum())
#print("Eoutput_sum\n", sum(Eoutput))

Whidden_output_sum1=Whidden_output.sum(axis=1, dtype='float')
print("Whidden_output_sum1\n", Whidden_output_sum1)
Whidden_output_norm=Whidden_output.T / Whidden_output_sum1.T
print("Whidden_output_norm\n", Whidden_output_norm)

Ehidden=np.dot(Whidden_output_norm, Eoutput)
print("Ehidden\n", Ehidden)
print("Ehidden_sum\n", Ehidden.sum())
#print("Ehidden_sum\n", sum(Ehidden))

Winput_hidden_sum1=Winput_hidden.sum(axis=1, dtype='float')
print("Winput_hidden_sum1\n", Winput_hidden_sum1)
Winput_hidden_norm=Winput_hidden.T / Winput_hidden_sum1.T
print("Winput_hidden_norm\n", Whidden_output_norm)

Einput=np.dot(Winput_hidden_norm, Ehidden)
print("Einput\n", Einput)
print("Einput_sum\n", Einput.sum())
#print("Einput_sum\n", sum(Einput))

Winput_hidden
 [[3. 2.]
 [1. 7.]]
Whidden_output
 [[2. 3.]
 [1. 4.]]
Eoutput
 [[0.8]
 [0.5]]
Eoutput_sum
 1.3
Whidden_output_sum1
 [5. 5.]
Whidden_output_norm
 [[0.4 0.2]
 [0.6 0.8]]
Ehidden
 [[0.42]
 [0.88]]
Ehidden_sum
 1.3
Winput_hidden_sum1
 [5. 8.]
Winput_hidden_norm
 [[0.4 0.2]
 [0.6 0.8]]
Einput
 [[0.362]
 [0.938]]
Einput_sum
 1.3


In [4]:
# 3번 Weight Update
import numpy as np
import scipy.special

#actication_function=lambda x: scipy.special.expit(x)
actication_function=lambda x: 1/(1+np.exp(-x))

WInput_hidden=np.array([[3.0,2.0],[1.0,7.0]])
#WInput_hidden=np.matrix([[3.0,2.0],[1.0,7.0]])
print("WInput_hidden\n", WInput_hidden)

Whidden_output=np.array([[2.0,3.0],[1.0,4.0]])
#Whidden_output=np.matrix([[2.0,3.0],[1.0,4.0]])
print("Whidden_output\n", Whidden_output)

activation_function=lambda x: scipy.special.expit(x)

Ohidden=np.array([0.4,0.5], ndmin=2).T
print("Ohidden\n", Ohidden)

print("logit(0.4)\n", scipy.special.logit(0.4))
print("logit(0.5)\n", scipy.special.logit(0.5))
Xhidden=np.array([scipy.special.logit(0.4),scipy.special.logit(0.5)], ndmin=2).T
print("Xhidden.T\n", Xhidden)

print("inv(WInput_hidden)\n", np.linalg.inv(WInput_hidden))

Input=np.dot(np.linalg.inv(WInput_hidden), Xhidden)
#Input=np.array([-0.14938188,0.02134027], ndmin=2).T
#Input=np.matrix([[-0.14938188,0.02134027]])
print("Input\n", Input)
print("Input.T\n", Input.T)

Eoutput=np.array([0.8,0.5], ndmin=2).T
print("Eoutput\n", Eoutput)
print("Eoutput_sum\n", sum(Eoutput))

Whidden_output_sum1=Whidden_output.sum(axis=1, dtype='float')
print("Whidden_output_sum1\n", Whidden_output_sum1)
Whidden_output_norm=Whidden_output / Whidden_output_sum1
print("Whidden_output_norm\n", Whidden_output_norm)

Ehidden=np.dot(Whidden_output_norm.T, Eoutput)
print("Ehidden\n", Ehidden)
print("Ehidden_sum\n", sum(Ehidden))

WjkOj=np.dot(Whidden_output, Ohidden)
print("WjkOj\n", WjkOj)

S=activation_function(WjkOj)
print("S\n", S)

SS=np.multiply(S, (1.0 - S))
print("SS\n", SS)
PartialEoverPartialWjk = -np.dot(np.multiply(Eoutput, SS), Ohidden.T)
print("PartialEoverPartialWjk\n", PartialEoverPartialWjk)

Whidden_output = Whidden_output - (0.1 * PartialEoverPartialWjk)
print("new Whidden_output\n", Whidden_output)

WijOi=np.dot(WInput_hidden, Input)
#WijOi=np.dot(WInput_hidden, Input.T)
print("WijOi\n", WijOi)

S=activation_function(WijOi)
print("S\n", S)

SS=np.multiply(S, (1.0 - S))
print("SS\n", SS)

PartialEoverPartialWij = -np.dot(np.multiply(Ehidden, SS), Input.T)
#PartialEoverPartialWij = -np.dot(np.multiply(Ehidden, SS), Input)
print("PartialEoverPartialWij\n", PartialEoverPartialWij)

WInput_hidden = WInput_hidden - (0.1 * PartialEoverPartialWij)
print("new WInput_hidden\n", WInput_hidden)

WInput_hidden
 [[3. 2.]
 [1. 7.]]
Whidden_output
 [[2. 3.]
 [1. 4.]]
Ohidden
 [[0.4]
 [0.5]]
logit(0.4)
 -0.4054651081081643
logit(0.5)
 0.0
Xhidden.T
 [[-0.40546511]
 [ 0.        ]]
inv(WInput_hidden)
 [[ 0.36842105 -0.10526316]
 [-0.05263158  0.15789474]]
Input
 [[-0.14938188]
 [ 0.02134027]]
Input.T
 [[-0.14938188  0.02134027]]
Eoutput
 [[0.8]
 [0.5]]
Eoutput_sum
 [1.3]
Whidden_output_sum1
 [5. 5.]
Whidden_output_norm
 [[0.4 0.6]
 [0.2 0.8]]
Ehidden
 [[0.42]
 [0.88]]
Ehidden_sum
 [1.3]
WjkOj
 [[2.3]
 [2.4]]
S
 [[0.90887704]
 [0.9168273 ]]
SS
 [[0.08281957]
 [0.076255  ]]
PartialEoverPartialWjk
 [[-0.02650226 -0.03312783]
 [-0.015251   -0.01906375]]
new Whidden_output
 [[2.00265023 3.00331278]
 [1.0015251  4.00190637]]
WijOi
 [[-4.05465108e-01]
 [ 2.77555756e-17]]
S
 [[0.4]
 [0.5]]
SS
 [[0.24]
 [0.25]]
PartialEoverPartialWij
 [[ 0.01505769 -0.0021511 ]
 [ 0.03286401 -0.00469486]]
new WInput_hidden
 [[2.99849423 2.00021511]
 [0.9967136  7.00046949]]


In [5]:
# 4번 forward232
import numpy as np
import scipy.special

#actication_function=lambda x: scipy.special.expit(x)
actication_function=lambda x: 1/(1+np.exp(-x))

Input=np.array([0.9,0.8], ndmin=2).T
#Input=numpy.matrix([[0.9],[0.8]])
print("input.T\n", input)

Winput_hidden=np.matrix([[0.9,0.4],[0.2,0.2],[0.1,0.6]])

print("Winput_hidden\n", Winput_hidden)

Whidden_output=np.matrix([[0.3,0.7,0.5],[0.8,0.1,0.5]])
print("Whidden_output\n", Whidden_output)

Xhidden=np.dot(Winput_hidden,Input)
print("Xhidden\n", Xhidden)

Ohidden=actication_function(Xhidden)
print("Ohidden\n", Ohidden)

Xoutput=np.dot(Whidden_output,Ohidden)
print("Xoutput\n", Xoutput)

output=actication_function(Xoutput)
print("output\n", output)

input.T
 <bound method Kernel.raw_input of <ipykernel.ipkernel.IPythonKernel object at 0x000001E00C10CEC8>>
Winput_hidden
 [[0.9 0.4]
 [0.2 0.2]
 [0.1 0.6]]
Whidden_output
 [[0.3 0.7 0.5]
 [0.8 0.1 0.5]]
Xhidden
 [[1.13]
 [0.34]
 [0.57]]
Ohidden
 [[0.7558389 ]
 [0.58419052]
 [0.63876318]]
Xoutput
 [[0.95506662]
 [0.98247176]]
output
 [[0.72213297]
 [0.72759839]]


In [6]:
# 5번 forward333 역전파 오차 값과 가중치 업데이트를 계산
import numpy as np
import scipy.special

# 학습률
leraning_rate=0.1

Winput_hidden=np.matrix([[0.9,0.3,0.4],[0.2,0.8,0.2],[0.1,0.5,0.6]])
print("Winput_hidden\n", Winput_hidden)

Whidden_output=np.matrix([[0.3,0.7,0.5],[0.6,0.5,0.2],[0.8,0.1,0.9]])
print("Whidden_output\n", Whidden_output)

targets = np.array([0.01, 0.01, 0.99], ndmin=2).T
output=np.array([0.726,0.708,0.778], ndmin=2).T
Eoutput=np.absolute(output-targets)
print("Eoutput\n", Eoutput)
print("Eoutput_sum\n", Eoutput.sum())
#print("Eoutput_sum\n", sum(Eoutput))

Whidden_output_sum1=Whidden_output.sum(axis=1, dtype='float')
print("Whidden_output_sum1\n", Whidden_output_sum1)
Whidden_output_norm=Whidden_output.T / Whidden_output_sum1.T
print("Whidden_output_norm\n", Whidden_output_norm)

Ehidden=leraning_rate*np.dot(Whidden_output_norm,Eoutput)
print("Ehidden\n", Ehidden)
print("Ehidden_sum\n", Ehidden.sum())
#print("Ehidden_sum\n", sum(Ehidden))

Winput_hidden_sum1=Winput_hidden.sum(axis=1, dtype='float')
print("Winput_hidden_sum1\n", Winput_hidden_sum1)
Winput_hidden_norm=Winput_hidden.T / Winput_hidden_sum1.T
print("Winput_hidden_norm\n", Whidden_output_norm)

Einput=leraning_rate*np.dot(Winput_hidden_norm, Ehidden)
print("Einput\n", Einput)
print("Einput_sum\n", Einput.sum())
#print("Einput_sum\n", sum(Einput))

Winput_hidden
 [[0.9 0.3 0.4]
 [0.2 0.8 0.2]
 [0.1 0.5 0.6]]
Whidden_output
 [[0.3 0.7 0.5]
 [0.6 0.5 0.2]
 [0.8 0.1 0.9]]
Eoutput
 [[0.716]
 [0.698]
 [0.212]]
Eoutput_sum
 1.626
Whidden_output_sum1
 [[1.5]
 [1.3]
 [1.8]]
Whidden_output_norm
 [[0.2        0.46153846 0.44444444]
 [0.46666667 0.38461538 0.05555556]
 [0.33333333 0.15384615 0.5       ]]
Ehidden
 [[0.05595761]
 [0.06143726]
 [0.04520513]]
Ehidden_sum
 0.1626
Winput_hidden_sum1
 [[1.6]
 [1.2]
 [1.2]]
Winput_hidden_norm
 [[0.2        0.46153846 0.44444444]
 [0.46666667 0.38461538 0.05555556]
 [0.33333333 0.15384615 0.5       ]]
Einput
 [[0.00454828]
 [0.00702857]
 [0.00468315]]
Einput_sum
 0.01626
